"""Add timestamps to Entry model

Revision ID: 34abbda346fb
Revises: 7a049ed81e69
Create Date: 2024-08-18 04:20:32.022644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34abbda346fb'
down_revision: Union[str, None] = '7a049ed81e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'created_at')
    # ### end Alembic commands ###
