"""add tables

Revision ID: 6cdd237774df
Revises: 
Create Date: 2024-08-17 11:41:45.092818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdd237774df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('clerkId', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerkId'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entryId', sa.String(), nullable=False),
    sa.Column('isComplaint', sa.Boolean(), nullable=False),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('subProduct', sa.String(), nullable=True),
    sa.Column('issue', sa.String(), nullable=True),
    sa.Column('subIssue', sa.String(), nullable=True),
    sa.Column('entryText', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('dateSentToCompany', sa.DateTime(), nullable=True),
    sa.Column('dateReceived', sa.DateTime(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('companyResponse', sa.String(), nullable=True),
    sa.Column('companyPublicResponse', sa.String(), nullable=True),
    sa.Column('consumerDisputed', sa.String(), nullable=True),
    sa.Column('consumerConsentProvided', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipCode', sa.String(), nullable=True),
    sa.Column('submittedVia', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('timely', sa.Boolean(), nullable=True),
    sa.Column('productCategory', sa.String(), nullable=True),
    sa.Column('subProductCategory', sa.String(), nullable=True),
    sa.Column('vectorId', sa.String(), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entryId')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'AUDIO', 'JSON', name='filetype'), nullable=False),
    sa.Column('entryId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entryId'], ['entry.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.drop_table('entry')
    op.drop_table('user')
    # ### end Alembic commands ###
