"""update entry fields

Revision ID: d140895c87f8
Revises: 6cdd237774df
Create Date: 2024-08-17 12:15:08.507674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd140895c87f8'
down_revision: Union[str, None] = '6cdd237774df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'issue')
    op.drop_column('entry', 'subProductCategory')
    op.drop_column('entry', 'consumerDisputed')
    op.drop_column('entry', 'zipCode')
    op.drop_column('entry', 'state')
    op.drop_column('entry', 'consumerConsentProvided')
    op.drop_column('entry', 'submittedVia')
    op.drop_column('entry', 'timely')
    op.drop_column('entry', 'tags')
    op.drop_column('entry', 'productCategory')
    op.drop_column('entry', 'dateReceived')
    op.drop_column('entry', 'companyResponse')
    op.drop_column('entry', 'companyPublicResponse')
    op.drop_column('entry', 'dateSentToCompany')
    op.drop_column('entry', 'vectorId')
    op.drop_column('entry', 'company')
    op.drop_column('entry', 'subIssue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('subIssue', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('vectorId', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('dateSentToCompany', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('companyPublicResponse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('companyResponse', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('dateReceived', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('productCategory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('timely', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('submittedVia', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('consumerConsentProvided', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('zipCode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('consumerDisputed', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('subProductCategory', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('entry', sa.Column('issue', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
